---
title: "和歌山県報告書(under working for final report)"
subtitle: "健康寿命"
author: "李鍾賛(jc lee, 滋賀大助教、数理統計学博士)"
date: "最終更新: `r format(Sys.time(), '%Y/%m/%d')`"
output:
  # word_document:
  html_document:
   number_section: true
   toc: true
   code_folding: hide
   # toc_float:
   #   smooth_scroll: false
   #   collapsed: false

# output:
#   ioslides_presentation:
#   widescreen: true
#   number_section: true
#   toc: true
#   transition: faster
  # css: 'scrollable_slides.css'

# runtime: shiny
# https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html

# The following single character keyboard shortcuts enable alternate display modes:
#
# 'f': enable fullscreen mode
#
# 'w': toggle widescreen mode
#
# 'o': enable overview mode
#
# 'h': enable code highlight mode
#
# 'p': show presenter notes
---
```{r}
```


# 
```{r}

# devtools::install_github(repo = "luka3117/JcPackage/OsakaUniv2020")

# 使用package
suppressMessages(library(readxl))
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(kableExtra))
suppressMessages(library(curl))
suppressMessages(library(tidyverse))
suppressMessages(library(plotly))
suppressMessages(library(ggrepel))

load("../ScreenEnd.RData")
```

# regression{.tabset .tabset-fade .tabset-pills}

  - only the followings are valid obj
  - d , var, pref_id
  - d_f_merge_X, d_m_merge_X, y_f , y_m
  - LE_d_f_final, HLE_d_f_final, LE_d_m_final, HLE_d_m_final


<!-- ```{r child="ref1.Rmd"} -->
<!-- ``` -->

## regression `LE_d_f_final`: 女性、平均寿命
```{r}
# -----------------
# Q1:Do the final regression and interprete : with 4 data
# -----------------
# ----------------- ----------------- ----------------- -----------------
#  _____ _             _   _     __  __
# |  ___(_)_ __   __ _| | | |   |  \/  |
# | |_  | | '_ \ / _` | | | |   | |\/| |
# |  _| | | | | | (_| | | | |___| |  | |
# |_|   |_|_| |_|\__,_|_| |_____|_|  |_|
# ----------------- ----------------- ----------------- -----------------

options(digits = 5)              # Modify global options

lm(LE_2015~. , data = LE_d_f_final) %>%
  broom::tidy() %>%
  left_join(var, by=c("term"="var_name_Eng")) %>%
  select(term, var_name_Jpn, everything(), -id,- address, -std.error, -columm_letter ) %>% DT::datatable() %>% DT::formatRound(columns=c('estimate', 'statistic', "p.value"), digits=3)

```




# -----------------
# Q2:logistic regression the final regression and interprete
# -----------------


# try glmm and  interprete

# find correlated variable

# data 標準化
<!-- d_common_standarize<- -->
<!-- d_common %>% dplyr::select_if(is.numeric) %>% -->
<!--   select(-key, -pref.id) %>% scale() %>% tbl_df() -->





