---
title: "和歌山県報告書(under working for final report)"
subtitle: "データ情報"
author: "李鍾賛(jc lee, 滋賀大助教、数理統計学博士)"
date: "最終更新: `r format(Sys.time(), '%Y/%m/%d')`"
output:
  # word_document:
  html_document:
  number_section: true
toc: true
code_folding: hide
toc_float:
  smooth_scroll: false
collapsed: false

# output:
#   ioslides_presentation:
#   widescreen: true
#   number_section: true
#   toc: true
#   transition: faster
# css: 'scrollable_slides.css'

# runtime: shiny
# https://bookdown.org/yihui/rmarkdown/ioslides-presentation.html

# The following single character keyboard shortcuts enable alternate display modes:
#
# 'f': enable fullscreen mode
#
# 'w': toggle widescreen mode
#
# 'o': enable overview mode
#
# 'h': enable code highlight mode
#
# 'p': show presenter notes
---


```{r}
# 使用package
suppressMessages(library(readxl))
suppressMessages(library(dplyr))
suppressMessages(library(data.table))
suppressMessages(library(kableExtra))
suppressMessages(library(curl))
suppressMessages(library(tidyverse))
suppressMessages(library(plotly))

load("ScreenEnd.RData")

```

# data {.tabset .tabset-fade .tabset-pills}

## common data `r d_common %>% dim() %>% .[2]-6`個の変数
```{r}
d_common %>% DT::datatable()
d_common
```

## 男性分データ`r d_mf %>% dim() %>% .[2]-6`個の変数

```{r}
d_mf %>% DT::datatable()
```

## 変数情報
```{r}
var %>% DT::datatable()
```

